#!/bin/bash

# This script takes a Gnome release number and a file with info about
# each module and sets up the necessary directories and symlinks (or
# copies) to put all the tarballs in a
#   $FTPROOT/$SUITE_TYPE/$MAJOR_MINOR/$VERSION/sources/$SUBDIR
# hierarchy.  (Here $SUITE_TYPE is e.g. desktop or bindings, $VERSION is
# something like 2.11.90, $MAJOR_MINOR would be 2.11 in that case, and
# $SUBDIR can be something like 'perl' though it is often blank.
# Search path for finding where to get the tarball from is as follows:
#   1) Look under 
#        $FTPROOT/sources/$MODULE/$MAJMIN/$MODULE-$VERSION.tar.gz
#      and make a symlink to that if it exists
#   2) If not found in step -1-, look under
#        ./$SUBDIR
#      and copy the file to the destination if that exists
#   3) If not found in step -1- or -2-, complain.
#
# This script will modify the files on the ftp server and create
# SHA256SUMS-for-gz and SHA256SUMS-for-bz2 files in the current directory.
#
# Input is of the form
#   release-suites <version> <datafile>
# where <version> is something like 2.11.90 and <datafile> is a file with
# lines of the form
#     SUITE:MODULE:VERSION:SUBDIR
# where SUBDIR can be blank.  Lines can also be entirely blank or
# begin with a '#' character to specify a comment that should be
# ignored.  Some examples:
#     platform:gtk+:2.7.2:
#     desktop:ggv:2.11.0:
#     # Here is a comment
#     bindings:gconfmm:2.10.0:c++
# If SUITE corresponds to a directory that doesn't exist, you'll need to
# create it on the server manually.  E.g.  mkdir /ftp/pub/gnome/admin.
# No, this script won't be modified to account for that or else it can't
# catch typos.
#
# Output consists only of errors and a short blurb about tarball size
# statistics for the release.
#
# NOTE: If for some reason your use of this script was in error
# (e.g. one of the tarball versions in your datafile were
# out-of-date), you can run e.g.
#   rm -rf /ftp/pub/GNOME/{core,apps}/*/2.11.57/
# and then re-run release-suites.  If you do this make sure to replace
# 2.11.57 with the right version.

FTPROOT=/ftp/pub/GNOME

majmin() {
	echo $1 | sed "s#\([[:digit:]]\+\.[[:digit:]]\+\).*#\1#"
}

if [ $# -ne 2 ]; then
	echo "Usage: $0 <version> <datafile>"
	exit 1
fi

RVERSION="$1"
RDATA="$2"

RSUITES="$(grep -v "\(^$\|^#\)" $RDATA | cut -d : -f 1 | sort | uniq | tr '\n' ' ')"
RMAJMIN="$(majmin $RVERSION)"

for suite in $RSUITES; do
	# check if the suite exists at all: exists == good
	if [ ! -d $FTPROOT/$suite ]; then
		echo "$suite suite does not exist!"
		exit 1
	fi
	# check if the version exists: exists == bad
	if [ -d $FTPROOT/$suite/$RMAJMIN/$RVERSION ]; then
		echo "$suite $RVERSION in the way!"
		exit 1
	else
		mkdir -p $FTPROOT/$suite/$RMAJMIN/$RVERSION/sources
	fi
done

# Read release data and create links
grep -v "\(^$\|^#\)" $RDATA | while read MDATA; do
	SUITE=$(echo $MDATA | cut -d : -f 1)
	MODULE=$(echo $MDATA | cut -d : -f 2)
	VERSION=$(echo $MDATA | cut -d : -f 3)
	SUBDIR=$(echo $MDATA | cut -d : -f 4)
	MAJMIN=$(majmin $VERSION)

	if [ -z "$SUBDIR" ]; then
		RDIR=$FTPROOT/$SUITE/$RMAJMIN/$RVERSION/sources
		RELATIVE="../../../.."
	else
		RDIR=$FTPROOT/$SUITE/$RMAJMIN/$RVERSION/sources/$SUBDIR
		if [ ! -d $RDIR ]; then
			mkdir -p $RDIR
		fi
		RELATIVE="../../../../.."
	fi
	
	if [ -f $FTPROOT/sources/$MODULE/$MAJMIN/$MODULE-$VERSION.tar.gz ]; then
		ln -s $RELATIVE/sources/$MODULE/$MAJMIN/$MODULE-$VERSION.tar.{gz,bz2} $RDIR/
	elif [[ -d ./$SUBDIR && -f ./$SUBDIR/$MODULE-$VERSION.tar.gz ]]; then
		cp -a ./$SUBDIR/$MODULE-$VERSION.tar.gz $RDIR/
	else
		echo "$MODULE $VERSION is not available."
	fi
done

for suite in $RSUITES; do
	cd $FTPROOT/$suite/$RMAJMIN/$RVERSION/sources
	sha256sum *.gz  */*.gz  > SHA256SUMS-for-gz  2> /dev/null
	sha256sum *.bz2 */*.bz2 > SHA256SUMS-for-bz2 2> /dev/null
	echo
	echo "$suite $RVERSION statistics:"
	echo "  tar.gz:   $(du -Lch *.tar.gz */*.tar.gz 2> /dev/null | grep total$)"
	echo "  tar.bz2:  $(du -Lch *.tar.bz2 */*.tar.bz2 2> /dev/null | grep total$)"
done

for suite in $RSUITES; do
	# fix permissions
	chown -R :ftpadmin $FTPROOT/$suite/$RMAJMIN/$RVERSION
	chmod g+rwX,o+rX $FTPROOT/$suite/$RMAJMIN/$RVERSION
	find $FTPROOT/$suite/$RMAJMIN/$RVERSION -type d | xargs chmod g+s
        # Take care of parent directories too, as needed & able
        find $FTPROOT/$suite -type d -uid $(id -u) | xargs chown :ftpadmin
        find $FTPROOT/$suite -type d -uid $(id -u) | xargs chmod g+rwX
done

# return your seat backs into their upright and locked positions
cd -
