#!/bin/sh

# This script finds the difference in NEWS entries between two releases.
#
# This script does not modify anything (well, other than creating and
# deleting a direcory in /tmp)
#
# Input is of the form
#     release-news <old-directory> <new-directory>
#   e.g.
#     release-news /ftp/pub/GNOME/desktop/2.10/2.10.1/ \
#                  /ftp/pub/GNOME/desktop/2.10/2.10.2/
#
# Output looks like
#   ========================================
#    NEWS: gnome-keyring-0.4.3
#   ========================================
#   
#   Changes in version 0.4.3 are:
#   * Translation updates
#   * Fix bug in acl functions
#   * implement gnome_keyring_set_info
#   * add sync function for all operations
#   * fix leaks
#   
#
#   ========================================
#    UPDATED: gnome-mag-0.12.1
#   ========================================
#   
#   gnome-mag was updated without a NEWS entry.


if [ $# -ne 2 ]; then
	echo "Usage: release-news <sources-old> <sources-new>"
	exit 1
fi

ARC=gz
DEC=-z

OLD=$1
NEW=$2
TMP=/tmp/release-news-$USER-$$

mkdir -p $TMP

find $OLD $NEW -name "*.tar.$ARC" \
	| sed 's,.*/\(.*\),\1,' | sort | uniq -u \
	| sed 's,\(.*\)-[[:digit:]].*,\1,' | uniq -d \
	| while read MODULE; do
		# pull out the NEWS files, ensuring to refer to only two module dirs
		for ARCHIVE in $(find $OLD $NEW -name "$MODULE-[[:digit:]]*.tar.$ARC"); do
			MODVER=$(basename $ARCHIVE .tar.$ARC);
			tar -C $TMP $DEC -xf $ARCHIVE $MODVER/NEWS 2> /dev/null;
		done;

		# diff the news files
		if [ $(find $TMP/$MODULE*/NEWS 2> /dev/null | wc -l) -eq 2 ]; then
			diff -U 0 $TMP/$MODULE*/NEWS | sed '1,/^@@/d;/^@@/,$d;/^[^+]/d;s/^+//' \
				> $TMP/$MODULE.NEWS
		fi

		# provide output if there's a sensible diff
		if [ -f $TMP/$MODULE.NEWS ] && [ -s $TMP/$MODULE.NEWS ] \
			&& [ $(wc -l < $TMP/$MODULE.NEWS) -gt 2 ]; then
			
			# print separator
			echo ""
			echo "========================================"
			echo " NEWS: $MODVER"
			echo "========================================"
			echo ""
		
			cat $TMP/$MODULE.NEWS;
		else
			# print separator
			echo ""
			echo "========================================"
			echo " UPDATED: $MODVER"
			echo "========================================"
			echo ""
			echo "$MODULE was updated without a NEWS entry."
			echo ""
		fi
	done

rm -rf $TMP
