#!/bin/sh

SINCE="-6m"


# l10n components
wget -O bugzilla-l10n.csv "https://bugzilla.gnome.org/report.cgi?bug_id=&bug_status=RESOLVED&bugidtype=include&chfield=bug_status&chfieldfrom=$SINCE&product=l10n&resolution=FIXED,WONTFIX,NOTABUG,NOTGNOME,INCOMPLETE,INVALID&y_axis_field=component&action=wrap&ctype=csv&format=table"
# all products
wget -O bugzilla-products.csv "https://bugzilla.gnome.org/report.cgi?bug_id=&bug_status=RESOLVED&bugidtype=include&chfield=bug_status&chfieldfrom=$SINCE&resolution=FIXED,WONTFIX,NOTABUG,NOTGNOME,INCOMPLETE,INVALID&y_axis_field=product&action=wrap&ctype=csv&format=table"


