#!/bin/sh

while read release date; do
	SINCE="$UNTIL"
	UNTIL="$date"
	[ -z "$SINCE" ] && continue
	[ -z "$release" ] && continue

	mkdir -p "./$release"
	cd "./$release"

	../get-git-stats "$SINCE" "$UNTIL" | tee modules.csv
	cd ..
done < releases

