#!/bin/sh
# vim: set ts=4:

SINCE="2011-04-06"

statdir=`pwd`

mkdir -p top-10

> "$statdir"/all-authors

echo -e "module\tcommits\tcommitters\tauthors"

allcommits=0

for d in ~/src/*; do

	if [ ! -d "$d" ]; then
		continue
	fi

	# check it is from gnome
	cd "$d"
	git config --get remote.origin.url | grep -q gnome || continue

	module=$(basename "$d")

	# Total number of commits:
	commits=$(git log --after=$SINCE --pretty=oneline | wc -l)

	if [ "$commits" == "0" ]; then
		committers=0
		authors=0
	else
		allcommits=$[$allcommits+$commits]
			# Check how many different committers for that module exist:
			# note: This is case-specific

			git log --after=$SINCE --committer='' --pretty=format:"%ce" > "$statdir"/committers
			committers=$(sort -u "$statdir"/committers | wc -l)

			cat "$statdir"/committers >> "$statdir"/all-committers

			# Check how many different authors for that module exist:
			# note: This is case-specific
			git log --after=$SINCE --author='' --pretty=format:"%ae" > "$statdir"/authors
			authors=$(sort -u "$statdir"/authors | wc -l)

			# Get 10 most active authors for all the commits, sorted by number of commits:
			sort "$statdir"/authors | uniq -c | sort -rn | head -n 10 > "$statdir/top-10/$module.csv"

			cat "$statdir"/authors >> "$statdir"/all-authors

	fi

	echo -e "$module\t$commits\t$committers\t$authors"
done

cd "$statdir"

commits=$allcommits
committers=$(cat all-committers | sort -u | wc -l)
authors=$(cat all-authors | sort -u | wc -l)
echo -e "TOTAL\t$commits\t$committers\t$authors"

sort "$statdir"/all-authors | uniq -c | sort -rn > "$statdir/authors.csv"
sort "$statdir"/all-committers | uniq -c | sort -rn > "$statdir/committers.csv"

rm -f "$statdir/authors" "$statdir/committers"
